/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zdl_NDKTools */

#ifndef _Included_com_example_zdl_NDKTools
#define _Included_com_example_zdl_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zdl_NDKTools
 * Method:    runPcap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_zdl_NDKTools_runPcap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
